
services:
  eadkp-dev:
    extends:
      file: .eadkp/docker-compose.base.yml
      service: eadkp-dev
    build:
      context: .
      dockerfile: dockerfile
    container_name: ${PROJECT_NAME}
    working_dir: /workspace/${PROJECT_NAME}
    environment:
      - EADKP_PRIMARY_BUILD=1
    volumes:
      - ./:/workspace/${PROJECT_NAME}
      # Cargo registry and git cache
      - cargo-registry:/home/dev/.cargo/registry
      - cargo-git:/home/dev/.cargo/git

volumes:
  cargo-registry:
  cargo-git:

# X11 et Wayland support (normalement) !
# Pour Windows, WSL2 intègre un serveur X11, le lien avec le WM de Windows sera automatique.
# Pour MacOS, il faudra probablement installer un serveur X11 et le configurer manuellement.