
allow-branch = ["dev"]

tag-name = "v{{version}}"

push = false
publish = false

# Commands :
#
#   cargo release patch --execute
#   cargo release minor --execute
#   cargo release major --execute
#
# patch: Changement interne, qui n'ajoute ou modifie pas l'api publique (ex: fix bug, refactor, docs, etc.)
# minor: Ajout de fonctionnalités sans casser la compatibilité
# major: Changement de l'api publique, qui peut casser la compatibilité