[package]
allow-branch = ["dev"]

tag-name = "v{{version}}"
tag-message = "Release v{{version}}"

push = false
publish = false

# Commands :
#
#   cargo release patch --tag-message "msg"
#   cargo release minor --tag-message "msg"
#   cargo release major --tag-message "msg"
#
# patch: Changement interne, qui n'ajoute ou modifie pas l'api publique (ex: fix bug, refactor, docs, etc.)
# minor: Ajout de fonctionnalités sans casser la compatibilité
# major: Changement de l'api publique, qui peut casser la compatibilité