name: Rust CI

on:
  push:
    branches: [ "dev", "master", "main" ]
  pull_request:
    branches: [ "dev", "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: thumbv7em-none-eabihf

      - name: Full Build (Verify everything)
        # On lance le build complet. 
        # Cela va executer build.rs (npx nwlink + compilation C via arm-gcc)
        # puis compiler la logique Rust.
        run: cargo build --release --target thumbv7em-none-eabihf