name: Rust CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EADKP_PRIMARY_BUILD: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/Cargo.lock') }} # Use Cargo.lock to bust cache
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: Install just
        run: cargo install just

      - name: Build library for device
        run: cargo build --lib --release --target thumbv7em-none-eabihf

      - name: Build library for simulator
        run: cargo build --lib --release

      - name: Build all examples
        run: just exports

      - name: Show build output
        run: |
          just list_build_dir
          just list_binaries
          just list_nwa_symbols